spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

app:
  cors:
    allowed-origins: "https://d2hk3a4qv3wwww.cloudfront.net"
