# application-test.yml (테스트 전용 설정)
spring:
  # ✅ 리소스 서버 자동 설정 비활성화 → JWK 원격 호출 방지
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false

app:
  cognito:
    region: ap-northeast-2
    user-pool-id: test-pool-id
    client-id: test-client-id
    user-info-uri: https://test.example.com/oauth2/userInfo
  cors:
    allowed-origins: "http://localhost:3000"
