name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]


jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle Wrapper 스크립트(gradlew 및 관련 JAR) 무결성 검증
        uses: gradle/wrapper-validation-action@v3
        timeout-minutes: 2
        continue-on-error: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle 실행 환경 최적화 + 캐시
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build (includes spotless/checkstyle/test via `check` dependency)
        run: ./gradlew --no-daemon build
        env:
          SPRING_PROFILES_ACTIVE: test